export interface InfrastructureItem {
    id: number;
    name: string;
    year?: string;
    make: string;
    category: "machinery" | "instrument";
    details?: string;
}

export const machineryList: InfrastructureItem[] = [
    { id: 1, name: "CIRCULAR SAW CUTTING MACHINE", year: "2018", make: "ZEAL TECH AUTOMATION", category: "machinery" },
    { id: 2, name: "CIRCULAR SAW CUTTING MACHINE", year: "2021", make: "ZEAL TECH AUTOMATION", category: "machinery" },
    { id: 3, name: "U - DRILLING MACHINE", year: "2019", make: "PRECICUT TOOL", category: "machinery" },
    { id: 4, name: "U - DRILLING MACHINE", year: "2010", make: "STEEL TECH AUTOMATION", category: "machinery" },
    { id: 5, name: "CNC TURNING CENTER MIDAS 6 OLD", year: "2011", make: "GALAXY MIDAS 6", category: "machinery" },
    { id: 6, name: "CNC TURNING CENTER MIDAS NEW", year: "2014", make: "GALAXY MIDAS 6", category: "machinery" },
    { id: 7, name: "CNC TURNING CENTER MEDA", year: "2008", make: "GALAXY MIDAS 6", category: "machinery" },
    { id: 8, name: "CNC TURNING CENTER MIDAS 6", year: "2017", make: "GALAXY MIDAS 6", category: "machinery" },
    { id: 9, name: "DRILLING & TAPPING MACHINE", year: "2011", make: "PRECICUT TOOL", category: "machinery" },
    { id: 10, name: "VERTICAL MILLING CENTER GOURAV", year: "2011", make: "GAURAV BMV 35 TC220", category: "machinery" },
    { id: 11, name: "VERTICAL MILLING CENTER CHANDRA", year: "2011", make: "CHANDRA", category: "machinery" },
    { id: 12, name: "HYDRAULIC THREAD ROLLING MACHINE", year: "2017", make: "THREAd AID", category: "machinery" },
    { id: 13, name: "HYDRAULIC THREAD ROLLING MACHINE OLD", year: "2000", make: "VENKATESHWAR INDUSTRIES", category: "machinery" },
    { id: 14, name: "HYDRAULIC PRESSING MACHINE", year: "2005", make: "POLHYDRON PVT LTD", category: "machinery" },
    { id: 15, name: "HYDRAULIC PRESSING MACHINE", year: "2005", make: "LINER ASSEMBLY", category: "machinery" },
    { id: 16, name: "CNC TURNING CENTER MEDA 4I", year: "2009", make: "FINISH TURNING", category: "machinery" },
    { id: 17, name: "CNC CYLINDRICAL GRINDING MACHINE", year: "2012", make: "OUTER DIA SURFACE FINISH", category: "machinery" },
    { id: 18, name: "CNC TURNING CENTER MIDAS 6 PLUS", year: "2015", make: "FINISH TURNING", category: "machinery" },
    { id: 19, name: "CNC CYLINDRICAL GRINDING MACHINE", year: "2015", make: "OUTER DIA SURFACE FINISH", category: "machinery" },
    { id: 20, name: "CNC TURNING CENTER MIDAS 6 PLUS", year: "2016", make: "FINISH TURNING", category: "machinery" },
    { id: 21, name: "CNC CYLINDRICAL GRINDING MACHINE", year: "2017", make: "OUTER DIA SURFACE FINISH", category: "machinery" },
    { id: 22, name: "TROBE MACHINE", year: "2014", make: "PARTING", category: "machinery" },
    { id: 23, name: "HYDRAULIC PRESSING MACHINE", year: "2005", make: "LINER ASSEMBLY", category: "machinery" },
    { id: 24, name: "PUNCHING MACHINE", year: "2000", make: "PUNCHING", category: "machinery" },
    { id: 25, name: "BUFFING MACHINE", year: "2005", make: "BUFFING", category: "machinery" },
    { id: 26, name: "DRILLING & TAPPING MACHINE", year: "2019", make: "DRILLING & TAPPING", category: "machinery" },
    { id: 27, name: "EN SERIES ROTARY SCREW AIR COMPRESSOR", year: "2018", make: "AIR SUCK & STORE", category: "machinery" },
    { id: 28, name: "AIR COMPRESSOR", year: "2008", make: "AIR SUCK & STORE", category: "machinery" },
    { id: 29, name: "13*13 MANUAL SUPER LATHE M/C", year: "2000", make: "MANUAL", category: "machinery" },
    { id: 30, name: "TABLE GRINDING MACHINE", year: "2000", make: "MANUAL", category: "machinery" },
    { id: 31, name: "TABLE DRILLING MACHINE", year: "2000", make: "MANUAL", category: "machinery" },
    { id: 32, name: "TAP CHECK MACHINE", year: "2021", make: "X FLOW TECHNOLOGIES", category: "machinery" },
    { id: 33, name: "TAP CHECK MACHINE", year: "2021", make: "X FLOW TECHNOLOGIES", category: "machinery" },
    { id: 34, name: "ACE CNC LATHE MODEL: J 300 LM", year: "2021", make: "ACE DESIGNERS LTD.", category: "machinery" },
    { id: 35, name: "ACE CNC LATHE MODEL: J 300 LM", year: "2021", make: "ACE DESIGNERS LTD.", category: "machinery" },
    { id: 36, name: "ELGi Air Compressor Manual", year: "2014", make: "eLGI", category: "machinery" },
    { id: 37, name: "BOLT TIGHTNING MACHINE", year: "2021", make: "X FLOW TECHNOLOGIES", category: "machinery" },
    { id: 38, name: "BOLT TIGHTNING MACHINE", year: "2021", make: "X FLOW TECHNOLOGIES", category: "machinery" },
    { id: 39, name: "BOLT TIGHTNING MACHINE", year: "2021", make: "X FLOW TECHNOLOGIES", category: "machinery" },
    { id: 40, name: "HYDRAULIC THREAD ROLLING MACHINE", year: "2022", make: "THREAD AID", category: "machinery" },
    { id: 41, name: "MANUAL DRILLING TAPPING MACHINE", year: "2022", make: "RAJESH TRADERS RAJKOT", category: "machinery" },
    { id: 42, name: "AUTOMATIC PICK AND PLACE", year: "2022", make: "ARROWS ENGINEERING", category: "machinery" },
    { id: 43, name: "ROBOTIC ARM", year: "2022", make: "ARROWS ENGINEERING", category: "machinery" },
    { id: 44, name: "ACE CNC LATHE MODEL: J 300 LM", year: "2022", make: "ACE DESIGNERS LTD.", category: "machinery" },
    { id: 45, name: "ACE CNC LATHE MODEL: J 300 LM", year: "2022", make: "ACE DESIGNERS LTD.", category: "machinery" },
    { id: 46, name: "CNC CYLINDRICAL GRINDING MACHINE", year: "2022", make: "HI-LIFE", category: "machinery" },
    { id: 47, name: "BOLT TIGHTNING MACHINE", year: "2021", make: "X FLOW TECHNOLOGIES", category: "machinery" },
    { id: 48, name: "DRILLING & TAPPING MACHINE", year: "2022", make: "PRECICUT TOOL", category: "machinery" },
    { id: 49, name: "U-DRILLING MACHINE", year: "2022", make: "PRECICUT TOOL", category: "machinery" },
    { id: 50, name: "EN SERIES ROTARY SCREW AIR COMPRESSOR", year: "2023", make: "ELGI", category: "machinery" },
    { id: 51, name: "POLYTRON MILLING MACHINE", year: "2024", make: "TRISHUL", category: "machinery" },
];

export const instrumentList: InfrastructureItem[] = [
    { id: 101, name: "VMM MACHINE (non-contact measuring machine)", details: "400*200*100", make: "ESSON", category: "instrument" },
    { id: 102, name: "SURAFACE ROUGHNESS TESTER", details: "0.03 mm", make: "MITUTOYO", category: "instrument" },
    { id: 103, name: "DIGITAL VERNIER HEIGHT GUAGE", details: "0 - 300 mm", make: "BAKER", category: "instrument" },
    { id: 104, name: "DIGITAL VERNIER HEIGHT GUAGE", details: "0 - 300 mm", make: "YUZUKI", category: "instrument" },
    { id: 105, name: "DIGITAL VERNIER HEIGHT GUAGE", details: "0 - 300 mm", make: "YUZUKI", category: "instrument" },
    { id: 106, name: "VERNIER CALIPER DIGITAL", details: "0-150", make: "YUZUKI", category: "instrument" },
    { id: 107, name: "VERNIER CALIPER DIGITAL", details: "0 - 150", make: "INSIZE", category: "instrument" },
    { id: 108, name: "OUTSIDE MICROMETER (DIGITAL)", details: "0-25", make: "MITUTOYO", category: "instrument" },
    { id: 109, name: "OUTSIDE MICROMETER (DIGITAL)", details: "0-25", make: "MITUTOYO", category: "instrument" },
    { id: 110, name: "OUTSIDE MICROMETER (DIGITAL)", details: "0-25", make: "MITUTOYO", category: "instrument" },
    { id: 111, name: "OUTSIDE MICROMETER (DIGITAL)", details: "25-50", make: "MITUTOYO", category: "instrument" },
    { id: 112, name: "OUTSIDE MICROMETER (DIGITAL)", details: "25-50", make: "MITUTOYO", category: "instrument" },
    { id: 113, name: "OUTSIDE MICROMETER (DIGITAL)", details: "0-25", make: "MITUTOYO", category: "instrument" },
    { id: 114, name: "OUTSIDE MICROMETER (DIGITAL)", details: "25-50", make: "MITUTOYO", category: "instrument" },
    { id: 115, name: "OUTSIDE MICROMETER (DIGITAL)", details: "25-50", make: "MITUTOYO", category: "instrument" },
    { id: 116, name: "OUTSIDE MICROMETER", details: "0-25", make: "MITUTOYO", category: "instrument" },
    { id: 117, name: "OUTSIDE MICROMETER", details: "25-50", make: "MITUTOYO", category: "instrument" },
    { id: 118, name: "OUTSIDE MICROMETER", details: "25-50", make: "MITUTOYO", category: "instrument" },
    { id: 119, name: "OUTSIDE MICROMETER", details: "0-25", make: "MITUTOYO", category: "instrument" },
    { id: 120, name: "OUTSIDE MICROMETER", details: "0-25", make: "MITUTOYO", category: "instrument" },
    { id: 121, name: "OUTSIDE MICROMETER", details: "25-50", make: "MITUTOYO", category: "instrument" },
    { id: 122, name: "SNAP GAUGE", details: "13(-0.02)", make: "SAMARTH GAUGE TOOLS", category: "instrument" },
    { id: 123, name: "SNAP GAUGE", details: "13 (-0.1,-0.15)", make: "SAMARTH GAUGE TOOLS", category: "instrument" },
    { id: 124, name: "SNAP GAUGE", details: "18 (-0.05,-0.1)", make: "SAMARTH GAUGE TOOLS", category: "instrument" },
    { id: 125, name: "SNAP GAUGE", details: "13(-0.02)", make: "SAMARTH GAUGE TOOLS", category: "instrument" },
    { id: 126, name: "SNAP GAUGE", details: "13 (-0.1,-0.15)", make: "SAMARTH GAUGE TOOLS", category: "instrument" },
    { id: 127, name: "HARDNESS TESTING MACHINE", make: "MANUAL", category: "instrument" },
    { id: 128, name: "M8 THREAD PLUG GAUGE", make: "BAKER", category: "instrument" },
    { id: 129, name: "M10 THREAD PLUG GAUGE", make: "BAKER", category: "instrument" },
    { id: 130, name: "M12 THREAD PLUG GAUGE", make: "BAKER", category: "instrument" },
    { id: 131, name: "SURFACE PLATE 640*400 MM", make: "LUTHRA", category: "instrument" },
    { id: 132, name: "BENCH CENTER", make: "PRECESION", category: "instrument" },
];
